ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS quiet_hours_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS quiet_hours_start TIME DEFAULT '22:00',
  ADD COLUMN IF NOT EXISTS quiet_hours_end TIME DEFAULT '07:00',
  ADD COLUMN IF NOT EXISTS weekend_reminders BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS daily_summary_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS daily_summary_time TIME DEFAULT '21:00',
  ADD COLUMN IF NOT EXISTS missed_habit_reminder BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS milestone_notifications BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT NULL;

ALTER TABLE habits
  ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS reminder_time TIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS reminder_days SMALLINT[] DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS reminder_message TEXT DEFAULT NULL;
